var $jscomp={scope:{},inherits:function(b,c){function a(){}a.prototype=c.prototype;b.prototype=new a;b.prototype.constructor=b;for(var d in c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(c,d);e&&Object.defineProperty(b,d,e)}else b[d]=c[d]}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,c,a,d){if(c){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in a||(a[e]={});a=a[e]}b=b[b.length-1];d=a[b];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");$jscomp.owns=function(b,c){return Object.prototype.hasOwnProperty.call(b,c)};$jscomp.polyfill("Object.assign",function(b){return b?b:function(b,a){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(e)for(var f in e)$jscomp.owns(e,f)&&(b[f]=e[f])}return b}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var c=0;return $jscomp.iteratorPrototype(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(b,c){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var a=0,d={next:function(){if(a<b.length){var e=a++;return{value:c(e,b[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.fill",function(b){return b?b:function(b,a,d){var c=this.length||0;0>a&&(a=Math.max(0,c+a));if(null==d||d>c)d=c;d=Number(d);0>d&&(d=Math.max(0,c+d));for(a=Number(a||0);a<d;a++)this[a]=b;return this}},"es6-impl","es3");
var Charger=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.speed=2.5;a.hitPoint=1;a.score=10;a.anim=new Animator(a,"enemy/charger.png",Animator.TYPE.NONE);a.routine=[(new Movement(Movement.COND.Y)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_Y).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_Y),(new Movement(10)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_X).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(1E3)).add(Gizmo.TYPE.OWN,Gizmo.DEST.TO)];return a};$jscomp.inherits(Charger,Enemy);
var DragonBody=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.effectH=!1;a.effectV=!1;a.hitPoint=Number.MAX_SAFE_INTEGER;a.score=0;a.anim=new Animator(a,"enemy/dragonBody.png",Animator.TYPE.NONE);return a};$jscomp.inherits(DragonBody,Enemy);DragonBody.prototype.recalculation=function(){var b=Field.Instance;Enemy.prototype.recalculation.call(this);this.minX=-b.width;this.minY=-b.height;this.maxX=2*b.width;this.maxY=2*b.height};DragonBody.prototype.trigger=function(){};
var DragonHead=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.x=0<a.x?a.x+50:a.x-50;a.speed=.9;a.effectH=!1;a.hitPoint=200;a.score=1E3;a.radian=Math.PI;a.appears=!1;a.anim=new Animator(a,"enemy/dragonHead.png",Animator.TYPE.NONE);a.locus=[];a.body=[];for(var d=0;d<DragonHead.CNT_OF_BODY*DragonHead.STP_OF_BODY;d++)if(a.locus.push({x:a.x,y:a.y,radian:a.radian}),0==d%DragonHead.STP_OF_BODY){var e=new DragonBody(a.x,a.y);a.body.push(e)}a.chamberList=[new Chamber(TitanShot,80,1)];return a};
$jscomp.inherits(DragonHead,Enemy);DragonHead.prototype.recalculation=function(){var b=Field.Instance;Enemy.prototype.recalculation.call(this);this.minX=-b.width;this.minY=-b.height;this.maxX=2*b.width;this.maxY=2*b.height};DragonHead.prototype.eject=function(){Enemy.prototype.eject.call(this);this.body.forEach(function(b){b.hitPoint=0;b.explosion=Actor.MAX_EXPLOSION})};
DragonHead.prototype.move=function(b){var c=this,a=Math.trim(this.radian+1.8*this.closeGap(b));this.radian=this.dir=a;Enemy.prototype.move.call(this,b);this.chamberList.forEach(function(a){a.probe()});for(b=0;b<DragonHead.CNT_OF_BODY;b++){var a=this.body[b],d=this.locus[(b+1)*DragonHead.STP_OF_BODY-1];a.x=d.x;a.y=d.y;a.radian=d.radian}this.locus.unshift({x:this.x,y:this.y,radian:this.radian});this.locus.pop();if(this.appears){var e=[];this.chamberList.forEach(function(a){if(a=a.fire(c))a.dir=c.dir,
a.radian=c.dir,e.push(a)});return e}this.appears=!0;return this.body};DragonHead.CNT_OF_BODY=10;DragonHead.STP_OF_BODY=32;
var EnmBattery=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.speed=0;a.hitPoint=1;a.score=10;a.anim=new Animator(a,"enemy/battery.png",Animator.TYPE.NONE);a.base=new Image;a.base.src="img/enemy/batteryBase.png";a.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO)];a.isInverse=!1;var d=Field.Instance;if(d&&d.landform){var e={x:a.x,y:a.y+Landform.BRICK_WIDTH};d.landform.hitTest(e);a.isInverse=!e.walled}return a};$jscomp.inherits(EnmBattery,Enemy);
EnmBattery.prototype.drawNormal=function(b){this.isInverse?this.radian<-Math.SQ?this.radian=Math.PI:0>this.radian&&(this.radian=0):Math.SQ<this.radian?this.radian=Math.PI:0<this.radian&&(this.radian=0);Enemy.prototype.drawNormal.call(this,b);b.save();b.translate(this.x,this.y);this.isInverse&&b.rotate(Math.PI);b.drawImage(this.base,-this.hW,-this.hH);b.restore()};
var EnmBouncer=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.dir=0>=a.x?0:Math.PI;a.speed=2;a.gravity=.1;a.reaction=.95;a.hitPoint=3;a.score=50;a.shuttle=2;a.img.src="img/enemy/bouncer.png";return a};$jscomp.inherits(EnmBouncer,Enemy);
EnmBouncer.prototype.move=function(b){this.shuttle&&(0>this.x||Field.Instance.width+Landform.BRICK_WIDTH<this.x)&&(this.dir=Math.trim(this.dir+Math.PI),this.x=this.svX,this.dx=-this.dx,this.shuttle--);this.walled&&(this.x=this.svX,this.y=this.svY);return Enemy.prototype.move.call(this,b)};EnmBouncer.prototype.drawNormal=function(b){var c=Math.abs(this.dy),c=5>c?.75+c/20:1;b.save();b.translate(this.x,this.y);b.scale(1,c);b.drawImage(this.img,-this.hW,-this.hH);b.restore()};
var EnmCrab=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.gravity=.3;a.reaction=.4;a.speed=2;a.hitPoint=1;a.score=90;a.anim=new Animator(a,"enemy/crab.png",Animator.TYPE.X,8,1);a.routine=[(new Movement(Movement.COND.X)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(EnmCrab.WALK)).add(Gizmo.TYPE.OWN,Gizmo.DEST.RIGHT),(new Movement(Movement.COND.X)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(EnmCrab.WALK)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.LEFT)];return a};
$jscomp.inherits(EnmCrab,Enemy);EnmCrab.WALK=20;var EnmHanker=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.speed=.7;a.hitPoint=2;a.score=50;a.anim=new Animator(a,"enemy/hanker.png",Animator.TYPE.NONE);a.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO)];return a};$jscomp.inherits(EnmHanker,Enemy);
var EnmJerky=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.speed=1;a.hitPoint=1;a.score=10;a.anim=new Animator(a,"enemy/jerky.png",Animator.TYPE.NONE);a.routine=[(new Movement(Movement.COND.X)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_X).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(Movement.COND.Y)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_Y).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_Y)];return a};$jscomp.inherits(EnmJerky,Enemy);
var EnmJuno=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.dir=Math.PI;a.speed=1.5;a.hitPoint=16;a.score=750;a.anim=new Animator(a,"enemy/juno.png",Animator.TYPE.NONE);a.routine=[(new Movement(200)).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO),(new Movement(Number.MAX_VALUE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)];return a};$jscomp.inherits(EnmJuno,Enemy);
EnmJuno.prototype.recalculation=function(){var b=Field.Instance;Enemy.prototype.recalculation.call(this);this.minX=-b.width;this.minY=-b.height;this.maxX=2*b.width;this.maxY=2*b.height};var Hatch=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.z=1;a.speed=0;a.hitPoint=10;a.score=200;a.count=0;a.children=0;a.anim=new Animator(a,"enemy/hatch.png",Animator.TYPE.Y,1,2);a.isInverse=!1;var d=Field.Instance;if(d&&d.landform){var e={x:a.x,y:a.y+Landform.BRICK_WIDTH};d.landform.hitTest(e);a.isInverse=!e.walled}return a};
$jscomp.inherits(Hatch,Enemy);Hatch.prototype.move=function(b){Enemy.prototype.move.call(this,b);if(!(this.count++<Hatch.IDLE||0!=this.count%Hatch.INTERVAL||Hatch.CHILDREN<=this.children++||0<this.explosion))return[new Charger(this.x,this.y)]};Hatch.IDLE=30;Hatch.INTERVAL=8;Hatch.CHILDREN=20;
var Slur=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.dir=0>=a.x?0:Math.PI;a.step=Math.PI/8;a.speed=2;a.hitPoint=3;a.score=300;a.anim=new Animator(a,"enemy/slur.png",Animator.TYPE.NONE);a.routine=[(new Movement(Slur.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(4*Slur.RANGE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE),(new Movement(Slur.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),
(new Movement(4*Slur.RANGE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)];return a};$jscomp.inherits(Slur,Enemy);Slur.RANGE=4;var Tentacle=function(b,c){var a;a=Chain.call(this,b,c)||this;a.speed=.6;a.hitPoint=16;a.appears=!1;a.anim=new Animator(a,"enemy/tentacle.png",Animator.TYPE.NONE);a.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO)];a.push(new TentacleHead(5+Tentacle.MAX_JOINT));for(var d=0;d<Tentacle.MAX_JOINT;d++)a.push(new TentacleJoint(5+Tentacle.MAX_JOINT-d));a.score=150;return a};
$jscomp.inherits(Tentacle,Chain);Tentacle.prototype.eject=function(){for(var b=this.next;b;)b.eject(),b=b.next;this.isGone=!0;this.x=-this.width};Tentacle.prototype.move=function(b){this.radius=this.hitPoint/2+8;this.scale=this.radius/Tentacle.MAX_RADIUS;Chain.prototype.move.call(this,b);this.radian=this.next.radian;if(!this.appears){this.appears=!0;b=[];for(var c=this.next;c;)b.push(c),c=c.next;return b}};Tentacle.prototype.trigger=function(){};Tentacle.MAX_JOINT=8;Tentacle.MAX_RADIUS=16;
Tentacle.DEG_STEP=Math.PI/2E3;var TentacleJoint=function(b){var c;c=Chain.call(this,0,0)||this;c.hasBounds=!1;c.radius=4;c.radian=0;c.speed=b;c.anim=new Animator(c,"enemy/tentacleJoint.png",Animator.TYPE.NONE);return c};$jscomp.inherits(TentacleJoint,Chain);TentacleJoint.prototype.addRadian=function(b){return this.radian=Math.trim(this.radian+b)};
TentacleJoint.prototype.move=function(b){b=Math.close(this.radian,Math.atan2(b.y-this.y,b.x-this.x),Tentacle.DEG_STEP*this.speed);var c=Math.trim(b-this.radian);b=this.prev;var c=this.addRadian(c),a=this.radius+b.radius;this.x=b.x+Math.cos(c)*a;this.y=b.y+Math.sin(c)*a};TentacleJoint.prototype.fate=function(){};TentacleJoint.prototype.trigger=function(){};var TentacleHead=function(b){b=TentacleJoint.call(this,0,0)||this;b.anim=new Animator(b,"enemy/tentacleHead.png",Animator.TYPE.NONE);return b};
$jscomp.inherits(TentacleHead,TentacleJoint);
var Twister=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.dir=0>=a.x?0:Math.PI;a.step=Math.PI/23;a.speed=3;a.score=100;a.anim=new Animator(a,"enemy/twister.png",Animator.TYPE.NONE);a.routine=[(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,
Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE)];return a};$jscomp.inherits(Twister,Enemy);Twister.RANGE=13;
var Waver=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.dir=0>=a.x?0:Math.PI;a.step=Math.PI/60;a.speed=2;a.score=10;a.anim=new Animator(a,"enemy/waver.png",Animator.TYPE.Y,1,8);a.routine=[(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L)];return a};$jscomp.inherits(Waver,Enemy);
Waver.RANGE=16;var Molten=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.dir=0;a.speed=.5;a.effectH=!1;a.hitPoint=Number.MAX_SAFE_INTEGER;a.cycle=0;a.phase=Molten.PHASE.TARGET;a.rock=[];a.appears=!1;a.anim=new Animator(a,"boss/molten.png",Animator.TYPE.NONE);a.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)];return a};$jscomp.inherits(Molten,Enemy);
Molten.prototype.move=function(b){Enemy.prototype.move.call(this,b);Molten.MAX_CYCLE<this.cycle++&&(this.cycle=0,this.phase++,this.phase%=Molten.PHASE.length);if(this.appears)return this.checkDestroy(b),[];this.appears=!0;b=new MoltenRock(this,this.x,this.y);this.rock=[b];return[b]};Molten.prototype.checkDestroy=function(b){var c=[];this.rock.forEach(function(a){a.isGone||c.push(a)});0==c.length&&(this.hitPoint=0,this.fate(b));this.rock=c};Molten.MAX_CYCLE=700;Molten.PHASE={OWN:0,TARGET:1,length:2};
var MoltenRock=function(b,c,a){c=Enemy.call(this,c,a)||this;c.hasBounds=!1;c.parent=b;c.dir=0;c.speed=.7;c.hitPoint=5;c.score=10;c.anim=new Animator(c,"boss/moltenRock.png",Animator.TYPE.NONE);c.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)];return c};$jscomp.inherits(MoltenRock,Enemy);
MoltenRock.prototype.move=function(b){var c=[],a=this.parent;a.phase==Molten.PHASE.OWN?c=Enemy.prototype.move.call(this,a):Enemy.prototype.move.call(this,b);if(this.absorbed&&this.hitPoint){b=Math.trim(this.dir+Math.SQ);for(var d=0;3>d;d++){var e=new MoltenRock(a,this.x,this.y);e.dir=b;e.speed=1.2*this.speed;e.hitPoint=this.hitPoint;c.push(e);a.rock.push(e);b=Math.trim(b+Math.SQ)}}this.absorbed=!1;return c};function MotionManager(){Repository.apply(this,arguments)}MotionManager.prototype=Object.create(Repository.prototype);
MotionManager.INSTANCE=new MotionManager;MotionManager.prototype.makeName=function(b){return"motion/"+b+".json"};function Motion(b,c,a,d){this.type=b;this.key=c;this.speed=a;this.h=d;this.y=this.x=this.v=0;this.triggerMax=this.triggerMin=Number.NaN;this.filling=this.reserve=null;this.batter=0}Motion.TYPE={NORMAL:0,ONLY_ONE:1,REWIND:2};Motion.prototype.rotateV=function(b){this.v=b;return this};Motion.prototype.offsetX=function(b){this.x=b;return this};
Motion.prototype.offsetY=function(b){this.y=b;return this};Motion.prototype.shot=function(b,c,a){this.reserve={type:b,id:c};isFinite(a)?(this.triggerMin=a,this.triggerMax=a+this.speed):(this.triggerMin=a.min,this.triggerMax=a.max);return this};Motion.prototype.reset=function(){if(this.mot=MotionManager.INSTANCE.dic[this.key])this.max=this.mot.length-1;this.ix=0;this.dir=1;return this};
Motion.prototype.next=function(){var b=this.ix+this.speed*this.dir;if(this.max<=b){if(this.type!=Motion.TYPE.REWIND)return null;this.ix=this.max;this.dir*=-1;return[this.mot[this.ix]]}if(0>b)return null;for(var c=[];this.ix!=b;)this.ix+=this.dir,c.push(this.mot[this.ix]);this.checkTrigger();return c};Motion.prototype.checkTrigger=function(){this.filling||(0<this.batter?this.batter=0:this.triggerMin<=this.ix&&this.ix<=this.triggerMax&&(this.filling=this.reserve,this.batter=1))};
Motion.prototype.fire=function(){if(this.filling){var b=this.filling;this.filling=null;return b}};function MotionRoutine(b){this.routine=b;this.ix=0;this.max=this.routine.length-1;this.loop=0;this.current=this.routine[this.ix].reset()}
MotionRoutine.prototype.next=function(b){var c=this.current.ix,a=this.current.next();null==a&&(this.ix++,this.max<this.ix&&(this.ix=0,this.loop++),this.current=this.routine[this.ix].reset(),0<this.loop&&this.current.type==Motion.TYPE.ONLY_ONE&&(this.ix++,this.current=this.routine[this.ix].reset()),a=this.current.next());var d=this.current.ix<c?-1:1,c=this.current.fire();b.rotationH=this.current.h;b.rotationV=this.current.v;b.offsetX=this.current.x;b.offsetY=this.current.y;b.calcRotationMatrix();a.forEach(function(a){b.shift(a,
d);b.calculate()});return c};function Skeleton(b){this.data=b;this.map={};this.offsetY=this.offsetX=0;this.rotationH=Math.PI/4;this.rotationV=Math.PI/8;this.rotationMatrix=new Matrix(Matrix.NO_EFFECT);this.init()}Skeleton.prototype.init=function(){var b=Object.assign(new Bone,this.data.root);this.data.root=b;this.prepare(b);this.calcRotationMatrix()};
Skeleton.prototype.prepare=function(b){var c=this,a=[];b.prepare();b.joint.forEach(function(c){c.parent=b;a.push(Object.assign(new Bone,c))});b.joint=a;b.joint.forEach(function(a){c.prepare(a)});b.skeleton=this;this.map[b.name]=b};Skeleton.prototype.calcRotationMatrix=function(){var b=Matrix.rotateY(this.rotationH);this.rotationMatrix=Matrix.rotateX(this.rotationV).multiply(b)};Skeleton.prototype.rotateH=function(b){this.rotationH+=Math.PI/720*b;this.rotationH=Math.trim(this.rotationH);this.calcRotationMatrix()};
Skeleton.prototype.rotateV=function(b){this.rotationV+=Math.PI/720*b;this.rotationV=Math.trim(this.rotationV);this.calcRotationMatrix()};Skeleton.prototype.shift=function(b,c){var a=this;b.forEach(function(b){var d=b.r,f=a.map[b.name],g=Matrix.rotateX(d.x),h=Matrix.rotateY(d.y),d=Matrix.rotateZ(d.z);f.motionMatrix=d.multiply(h).multiply(g);b.p&&(b=b.p,g=f.pt,f.translateMatrix=new Matrix([[1,0,0,a.offsetX+g.x+b.x*c],[0,1,0,a.offsetY+g.y+b.y*c],[0,0,1,g.z+b.z*c],[0,0,0,1]]))})};
Skeleton.prototype.calculate=function(b){this.data.root.calculate(b)};Skeleton.prototype.draw=function(b){this.data.root.draw(b)};function Bone(){this.pt={x:0,y:0,z:0}}
Bone.prototype.prepare=function(){var b=this.translate,c=Matrix.rotateX(this.axis.x),a=Matrix.rotateY(this.axis.y),c=Matrix.rotateZ(this.axis.z).multiply(a).multiply(c);this.translateMatrix=new Matrix([[1,0,0,b.x],[0,1,0,b.y],[0,0,1,b.z],[0,0,0,1]]);if(this.parent){var d=this.parent,b=Matrix.rotateX(-d.axis.x),a=Matrix.rotateY(-d.axis.y),d=Matrix.rotateZ(-d.axis.z);this.axisMatrix=b.multiply(a).multiply(d).multiply(c)}else this.axisMatrix=c;this.motionMatrix=new Matrix(Matrix.NO_EFFECT)};
Bone.prototype.getAccum=function(){if(this.parent){var b=this.axisMatrix.multiply(this.motionMatrix).multiply(this.translateMatrix);return this.parent.getAccum().multiply(b)}return this.translateMatrix.multiply(this.motionMatrix)};Bone.prototype.calculate=function(b){this.pt=this.getAccum().affine(0,0,0);b||this.joint.forEach(function(b){b.calculate(!1)})};
Bone.prototype.drawLine=function(b){var c=this.parent.pt,a=this.pt,d=this.skeleton.rotationMatrix,c=d.affine(c.x,c.y,c.z),a=d.affine(a.x,a.y,a.z),d=a.x,e=-a.y,f=c.x,c=-c.y,g=d-f,h=e-c;this.cx=f+g/2;this.cy=c+h/2;this.cz=a.z;this.radian=Math.atan2(h,g);b.beginPath();b.moveTo(f,c);b.lineTo(d,e);b.stroke()};Bone.prototype.draw=function(b){this.calculate();this.parent&&this.drawLine(b);this.joint.forEach(function(c){c.draw(b)})};
var Titan=function(b,c){var a;a=Enemy.call(this,b,c)||this;var d=Object.assign({},MotionManager.INSTANCE.dic.asf);a.scale=7;a.hitPoint=Number.MAX_SAFE_INTEGER;a.motionRoutine=new MotionRoutine([(new Motion(Motion.TYPE.ONLY_ONE,"111_7.amc",2,Math.PI/4)).offsetX(0).offsetY(0),(new Motion(Motion.TYPE.NORMAL,"79_96.amc",1,.4*-Math.PI)).shot(TitanShot,["lradius","lwrist","lhand","lthumb","lfingers"],200),(new Motion(Motion.TYPE.REWIND,"133_01.amc",2,Math.PI)).shot(TitanBullet,["thorax","upperneck"],{min:200,
max:550}),(new Motion(Motion.TYPE.NORMAL,"79_91.amc",1,.4*-Math.PI)).shot(TitanBall,["rhumerus","rradius","rwrist","rhand"],{min:175,max:200}),(new Motion(Motion.TYPE.NORMAL,"86_01b.amc",2,Math.PI)).shot(Bullet,["lfingers","rfingers"],{min:0,max:1E3})]);d&&(a.skeleton=new Skeleton(d),a.setupBone());return a};$jscomp.inherits(Titan,Enemy);
Titan.prototype.setupBone=function(){var b={};Object.keys(this.skeleton.map).forEach(function(c){if("root"!=c){var a=new TitanBone(0,0);a.anim=new Animator(a,"boss/titan/"+c+".png",Animator.TYPE.NONE);"lowerback"==c&&(a.hitPoint=Titan.HIT_POINT);a.id=c;b[c]=a}});this.boneMap=b;this.appears=!1};Titan.prototype.eject=function(){var b=this;Enemy.prototype.eject.call(this);Object.keys(this.boneMap).forEach(function(c){c=b.boneMap[c];c.hitPoint=0;c.explosion=2*Actor.MAX_EXPLOSION})};
Titan.prototype.move=function(b){var c=[],a=this,d=this.motionRoutine.next(this.skeleton);Enemy.prototype.move.call(this,b);if(!this.appears)return Object.keys(this.boneMap).forEach(function(b){c.push(a.boneMap[b])}),this.appears=!0,c.reverse();var e=this.skeleton.map,f=!1;d&&d.id.forEach(function(b){b=a.boneMap[b];var e=new d.type(b.x,b.y);e.dir=b.radian;c.push(e)});Object.keys(this.boneMap).forEach(function(b){var c=e[b],d=c.cy*a.scale+a.y;b=a.boneMap[b];b.x=c.cx*a.scale+a.x;b.y=d;b.z=c.cz;b.radian=
c.radian;b.constraint=!0;0==b.hitPoint&&(f=!0)});f&&this.eject();return c};Titan.prototype.drawInfo=function(b){var c=this.motionRoutine.current,a=this.boneMap.lowerback;b.save();b.translate(this.x,this.y);b.strokeStyle="rgba(255, 255, 255, 0.8)";b.strokeText("ix:"+c.ix,0,0);b.strokeText("hp:"+a.hitPoint,0,10);b.restore()};
Titan.prototype.drawNormal=function(b){b.save();b.translate(this.x,this.y);this.skeleton&&(b.scale(this.scale,this.scale),b.strokeStyle="rgba(203, 152, 135, 0.2)",this.skeleton.draw(b));b.restore();this.drawInfo(b)};Titan.prototype.isHit=function(b){return!1};Titan.HIT_POINT=292;var TitanBone=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.hitPoint=Number.MAX_SAFE_INTEGER;a.filling=null;return a};$jscomp.inherits(TitanBone,Enemy);TitanBone.prototype.trigger=function(){};
TitanBone.prototype.drawNormal=function(b){Enemy.prototype.drawNormal.call(this,b)};var TitanBall=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.hasBounds=!1;a.speed=1.5+4*Math.random();a.gravity=.03;a.hitPoint=4;a.anim=new Animator(a,"boss/titan/titan.ball.png",Animator.TYPE.NONE);return a};$jscomp.inherits(TitanBall,Enemy);TitanBall.prototype.trigger=function(){};TitanBall.prototype.react=function(){Enemy.prototype.react.call(this);this.fate(this)};
var TitanBullet=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.dir=-Math.PI+Math.SQ/2;a.radian=a.dir;a.speed=4;a.hitPoint=Number.MAX_SAFE_INTEGER;a.anim=new Animator(a,"boss/titan/titan.bullet.png",Animator.TYPE.NONE);return a};$jscomp.inherits(TitanBullet,Enemy);TitanBullet.prototype.trigger=function(){};
var TitanShot=function(b,c){var a;a=Enemy.call(this,b,c)||this;a.dir=Math.PI;a.radian=a.dir;a.speed=7;a.hitPoint=Number.MAX_SAFE_INTEGER;a.anim=new Animator(a,"boss/titan/titan.shot.png",Animator.TYPE.NONE);return a};$jscomp.inherits(TitanShot,Enemy);
var Winding=function(b,c){var a;a=Chain.call(this,b,c)||this;a.dir=-Math.PI;a.step=Math.SQ/100;a.radius=Winding.RADIUS;a.speed=.9;a.hitPoint=150;a.hasBounds=!1;a.ratio=Winding.RATIO_MAX;a.delta=-1;a.uncoil=!1;a.anim=new Animator(a,"boss/winding.png",Animator.TYPE.NONE);a.routine=[(new Movement(200)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE),(new Movement(20)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R)];a.appears=!1;for(var d=0;d<Winding.MAX_JOINT;d++)a.push(new WindingChild(b,c));return a};
$jscomp.inherits(Winding,Chain);Winding.prototype.move=function(b){b=Chain.prototype.move.call(this,b);var c=Math.trim(this.dir-Math.SQ/2);this.rad=Math.trim(this.dir+Math.SQ);if(this.appears){for(var a=this.next;a;)c+=Winding.RADIAN_STEP*this.ratio/100,a.radian=Math.trim(c),a=a.next;this.uncoil&&(this.ratio+=this.delta,1>=this.ratio?this.delta*=-1:Winding.RATIO_MAX<=this.ratio&&(this.uncoil=!1,this.delta*=-1));return b}this.appears=!0;for(a=this.next;a;)b.push(a),a=a.next;return b};
Winding.prototype.fate=function(b){Chain.prototype.fate.call(this,b);this.uncoil=!0};Winding.RADIUS=16;Winding.RADIAN_STEP=Math.SQ;Winding.RATIO_MAX=50;Winding.MAX_JOINT=20;var WindingChild=function(b,c){var a;a=Chain.call(this,b,c)||this;a.hasBounds=!1;a.effectH=!1;a.radius=WindingChild.RADIUS;a.anim=new Animator(a,"boss/winding.joint.png",Animator.TYPE.NONE);return a};$jscomp.inherits(WindingChild,Chain);
WindingChild.prototype.move=function(b){b=this.prev;var c=this.radius+b.radius;this.x=b.x+Math.cos(this.radian)*c;this.y=b.y+Math.sin(this.radian)*c};WindingChild.prototype.fate=function(){};WindingChild.prototype.trigger=function(){};WindingChild.RADIUS=4;
var Cascade=function(b,c){var a;a=Chain.call(this,b,c)||this;a.anim=new Animator(a,"material/cascade.png",Animator.TYPE.NONE);a.radian=Math.SQ;a.radius=Cascade.RADIUS;a.appears=!1;for(var d=0;d<Cascade.MAX_JOINT;d++)a.push(new CascadeChild(b,c,3*(Cascade.MAX_JOINT-d)));return a};$jscomp.inherits(Cascade,Chain);Cascade.prototype.move=function(b){Chain.prototype.move.call(this,b);if(!this.appears){this.appears=!0;b=[];for(var c=this.next;c;)b.push(c),c=c.next;return b}};Cascade.prototype.fate=function(){};
Cascade.prototype.trigger=function(){};Cascade.RADIUS=4;Cascade.MAX_JOINT=12;var CascadeChild=function(b,c,a){b=Chain.call(this,b,c)||this;b.maxX=Field.Instance.width+100;b.effectH=!1;b.effectV=!1;b.weight=a;b.radian=.9*Math.SQ;b.radius=Cascade.RADIUS;b.step=0;return b};$jscomp.inherits(CascadeChild,Chain);CascadeChild.prototype.addRadian=function(b){return this.radian=Math.trim(this.radian+b)};
CascadeChild.prototype.move=function(b){b=this.prev;var c=Math.trim(Math.SQ-this.radian)/(300+10*this.weight);this.step+=c;0==parseInt(1E3*c)&&(this.step*=.98);var c=Math.trim(this.radian+this.step),a=this.radius+b.radius;0>c&&(c=0);this.radian=c;this.x=b.x+Math.cos(c)*a;this.y=b.y+Math.sin(c)*a};CascadeChild.prototype.draw=function(b){b.save();b.fillStyle="rgba(60, 200, 0, 0.8)";b.translate(this.x,this.y);b.beginPath();b.arc(0,0,this.radius,0,Math.PI2,!1);b.fill();b.restore()};
CascadeChild.prototype.fate=function(b){b=Math.PI/200;this.step-=b;for(var c=this.next;c;)c.step-=.8*b,c=c.next};CascadeChild.prototype.trigger=function(){};
var Rewinder=function(b,c){var a;a=Chain.call(this,b,c)||this;a.step=Math.SQ/100;a.radius=Rewinder.RADIUS;a.speed=1.1;a.hitPoint=Number.MAX_SAFE_INTEGER;a.hasBounds=!1;a.ratio=Rewinder.RATIO_MAX;a.delta=-.8;a.anim=new Animator(a,"material/cascade.png",Animator.TYPE.NONE);a.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO)];a.appears=!1;for(var d=0;d<Rewinder.MAX_JOINT;d++)a.push(new RewinderChild(b,c));return a};$jscomp.inherits(Rewinder,Chain);
Rewinder.prototype.move=function(b){var c=[],a=Math.trim(this.radian+Math.SQ/2);Chain.prototype.move.call(this,b);if(this.appears){for(b=this.next;b;)a-=Rewinder.RADIAN_STEP*this.ratio/100,b.radian=Math.trim(a),b=b.next;this.ratio+=this.delta;1>=this.ratio?this.delta*=-1:Rewinder.RATIO_MAX<=this.ratio&&(this.delta*=-1);return c}this.appears=!0;for(b=this.next;b;)c.push(b),b=b.next;return c};Rewinder.prototype.fate=function(){};Rewinder.RADIUS=4;Rewinder.RADIAN_STEP=Math.SQ;Rewinder.RATIO_MAX=100;
Rewinder.MAX_JOINT=16;var RewinderChild=function(b,c){var a;a=Chain.call(this,b,c)||this;a.radian=0;a.hasBounds=!1;a.effectH=!1;a.effectV=!1;a.radius=RewinderChild.RADIUS;a.anim=new Animator(a,"boss/winding.joint.png",Animator.TYPE.NONE);return a};$jscomp.inherits(RewinderChild,Chain);RewinderChild.prototype.move=function(b){b=this.prev;var c=this.radius+b.radius;this.x=b.x+Math.cos(this.radian)*c;this.y=b.y+Math.sin(this.radian)*c};RewinderChild.prototype.fate=function(){};RewinderChild.RADIUS=4;
Enemy.LIST=[{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Battery",type:EnmBattery,img:"enemy/battery.png"},{name:"Bouncer",type:EnmBouncer,img:"enemy/bouncer.png"},{name:"Hanker",type:EnmHanker,img:"enemy/hanker.png"},{name:"Jerky",type:EnmJerky,img:"enemy/jerky.png"},{name:"Juno",type:EnmJuno,img:"enemy/juno.png"},{name:"Crab",type:EnmCrab,img:"enemy/crab.png"},{name:"Hatch",type:Hatch,img:"enemy/hatch.png",h:16},{name:"Charger",type:Charger,img:"enemy/charger.png",h:16},{name:"Twister",
type:Twister,img:"enemy/twister.png",h:16},{name:"Slur",type:Slur,img:"enemy/slur.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",
h:16},{name:"Waver",type:Waver,img:"enemy/waver.png",h:16},{name:"Tentacle",type:Tentacle,img:"enemy/tentacle.png"},{name:"Dragon",type:DragonHead,img:"enemy/dragonHead.png"},{name:"Waver(formation)",type:Waver,img:"enemy/waver.png",h:16,formation:!0},{name:"Molten",type:Molten,img:"boss/molten.png"},{name:"Winding",type:Winding,img:"boss/winding.png"},{name:"Titan",type:Titan,img:"boss/titan.icon.png"},{name:"Cascade",type:Cascade,img:"material/cascade.icon.png"},{name:"Rewinder",type:Rewinder,img:"material/cascade.icon.png"}];
Stage.LIST=[(new Stage(Stage.SCROLL.OFF,"stage00map.png",[new StageBg("stage01bg0.png",.3),new StageBg("stage01bg1.png",.4,0,.02),new StageFg("stage00bg.png")])).setBgm("bgm-edo-beth"),(new Stage(Stage.SCROLL.OFF,"stage01map.png",[new StageBg("stage01bg1.png",.3,0,.02),new StageBg("stage01bg0.png",.3),new StageFg("stage01bg.png",.6)])).setBgm("bgm-MadNightDance","bgm-edo-omega-zero"),(new Stage(Stage.SCROLL.LOOP,"stage00map.png",[new StageBg("stage01bg0.png",.3),new StageBg("stage01bg1.png",.4,0,
.02),new StageFg("stage00bg.png")])).setBgm("bgm-edo-beth"),(new Stage(Stage.SCROLL.ON,"stage02map.png",[new StageBg("stage01bg1.png",.3),new StageBg("stage01bg0.png",.4),new StageFg("stage02bg.png")])).setBgm("bgm-pierrot-cards","bgm-edo-omega-zero"),(new Stage(Stage.SCROLL.OFF,"stage1.map.png",[new StageBg("stage01bg1.png",.3),new StageBg("stage01bg0.png",.4),new StageFg("stage1.1.0.png",.6)])).setBgm("bgm-ThroughTheDark","bgm-edo-omega-zero"),(new Stage(Stage.SCROLL.ON,"stage2.map.png",[new StageBg("stage2.1.1.png",
.3),new StageBg("stage01bg1.png",1,-Math.SQ/2),new StageFg("stage2.1.0.png")])).setBgm("bgm-pierrot-cards","bgm-edo-omega-zero"),(new Stage(Stage.SCROLL.OFF,"stage3.map.png",[new StageBg("stage01bg1.png",.3),new StageFg("stage3.1.1.png",.5,0,.02),new StageFg("stage3.1.0.png")])).setBgm("bgm-YourDream-R","bgm-edo-omega-zero"),(new Stage(Stage.SCROLL.LOOP,"stage4.map.png",[new StageBg("stage01bg1.png",.3),new StageFg("stage01bg0.png",.5,0,.02),new StageFg("stage4.1.0.png",.45)])).setBgm("bgm-MadNightDance",
"bgm-edo-omega-zero")];AudioMixer.INSTANCE.reserve(["sfx-fire","sfx-explosion","sfx-absorb"]);MotionManager.INSTANCE.reserve("asf 79_91.amc 79_96.amc 86_01b.amc 111_7.amc 133_01.amc".split(" "));
