var $jscomp={scope:{},inherits:function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)$jscomp.owns(e,f)&&(a[f]=e[f])}return a}},"es6-impl","es3");
function Actor(a,b,c){var d=this;this.field=a;this.x=b;this.y=c;this.dy=this.dx=this.z=0;this.dir=null;this.radian=0;this.height=this.width=16;this.reaction=this.gravity=this.margin=0;this.speed=1;this.effectV=this.effectH=!0;this.hitPoint=1;this.absorbed=!1;this.score=0;this.walled=!1;this.recalculation();this.img=new Image;this.img.onload=function(){d.width=this.width;d.height=this.height;d.recalculation()};this.sfx="sfx-explosion";this.sfxAbsorb="sfx-absorb";this.enter()}Actor.MAX_EXPLOSION=12;
Actor.DEG_STEP=Math.PI/180;Actor.prototype.recalculation=function(){this.hW=this.width/2;this.hH=this.height/2;this.minX=-this.width-this.margin;this.minY=-this.height-this.margin;this.maxX=this.field.width+this.width+this.margin;this.maxY=this.field.height+this.height+this.margin};Actor.prototype.enter=function(){this.explosion=0;this.isGone=!1};Actor.prototype.eject=function(){this.isGone=!0;this.x=-this.field.width};
Actor.prototype.aim=function(a){if(a){var b=this.calcDistance(a);this.speed<b&&(this.dir=Math.atan2(a.y-this.y,a.x-this.x))}else this.dir=null;return this};Actor.prototype.closeGap=function(a){a=Math.trim(this.radian-Math.atan2(a.y-this.y,a.x-this.x));return Math.abs(a)<=Actor.DEG_STEP?0:0<a?-Actor.DEG_STEP:Actor.DEG_STEP};
Actor.prototype.move=function(a){if(0<this.explosion&&(this.explosion--,0==this.explosion)){this.eject();return}this.svX=this.x;this.svY=this.y;null!=this.dir&&(this.x+=Math.cos(this.dir)*this.speed,this.y+=Math.sin(this.dir)*this.speed);if(0!=this.gravity){a=this.field.landform.scanFloor(this);var b=!1;0>this.gravity?(a+=this.hH,a<this.y?this.dy+=this.gravity:this.y<a&&(b=!0)):(a-=this.hH,this.y<a?this.dy+=this.gravity:a<this.y&&(b=!0));b&&(2*Landform.BRICK_WIDTH<Math.abs(this.y-a)?this.dir=Math.trim(this.dir+
Math.PI):(this.y=a,this.react()))}this.x+=this.dx*this.speed;this.y+=this.dy*this.speed;this.anim&&this.anim.next(this.dir)};Actor.prototype.react=function(){this.dy*=-this.reaction;this.radian=this.field.landform.getHorizontalAngle(this)};Actor.prototype.drawNormal=function(a){this.anim&&this.anim.draw(a)};Actor.prototype.drawExplosion=function(a){var b=this.explosion;a.fillStyle="rgba(255, 0, 0, 0.7)";a.save();a.translate(this.x,this.y);a.beginPath();a.arc(0,0,b,0,Math.PI2,!1);a.fill();a.restore()};
Actor.prototype.draw=function(a){this.isGone||(0<this.explosion?this.drawExplosion(a):this.drawNormal(a))};Actor.prototype.isHit=function(a){return this.isGone||0<this.explosion||0<a.explosion?!1:this.calcDistance(a)<(this.hW+a.hW+(this.hH+a.hH))/3?(this.fate(a),a.fate(this),!0):!1};Actor.prototype.calcDistance=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};
Actor.prototype.fate=function(a){this.isGone||this.explosion||(this.hitPoint--,0<this.hitPoint?this.absorb(a):(this.explosion=Actor.MAX_EXPLOSION,AudioMixer.INSTANCE.play(this.sfx,.2,!1,(this.x-Field.HALF_WIDTH)/Field.HALF_WIDTH)))};
Actor.prototype.absorb=function(a){this.absorbed=!0;if(this.sfxAbsorb){var b=this.field.ctx;b.fillStyle="rgba(255, 200, 0, 0.4)";b.save();b.translate(a.x,a.y);b.beginPath();b.arc(0,0,5,0,Math.PI2,!1);b.fill();b.restore();AudioMixer.INSTANCE.play(this.sfxAbsorb,.3,!1,(this.x-Field.HALF_WIDTH)/Field.HALF_WIDTH)}};function NOP(){}
function Animator(a,b,c){var d=this,e=arguments.length;this.actor=a;this.type=c;this.numX=3<e?arguments[3]:1;this.numY=4<e?arguments[4]:1;this.patNum=0;this.img=new Image;this.img.onload=function(){d.width=this.width/d.numX;d.height=this.height/d.numY;d.hW=d.width/2;d.hH=d.height/2;a.width=d.width;a.height=d.height;a.hW=d.hW;a.hH=d.hH;a.recalculation&&a.recalculation()};this.img.src="img/"+b}Animator.TYPE={NONE:0,X:1,Y:2,XY:3,H:4,V:5};
Animator.prototype.next=function(a){this.type==Animator.TYPE.V&&.1<Math.abs(this.patNum)&&(this.patNum=0>this.patNum?this.patNum+.1:this.patNum-.1);if(null!=a)if(this.type==Animator.TYPE.X)this.patNum+=.5*Math.cos(a),a=Math.floor(this.patNum),0>a?this.patNum=this.numX-.1:this.numX<=a&&(this.patNum=0);else if(this.type==Animator.TYPE.Y)this.patNum+=.5*Math.sin(a),a=Math.floor(this.patNum),0>a?this.patNum=this.numY-.1:this.numY<=a&&(this.patNum=0);else if(this.type==Animator.TYPE.V){var b=Math.floor(this.numY/
2);this.patNum+=Math.sin(a)/3;this.patNum<-b?this.patNum=-b:b<this.patNum&&(this.patNum=b)}this.patNum*=1E3;this.patNum=Math.round(this.patNum)/1E3};
Animator.prototype.draw=function(a){var b=this.actor,c=this.width,d=this.height,e=0,f=0;this.type==Animator.TYPE.X?e=c*Math.floor(this.patNum):this.type==Animator.TYPE.Y?f=d*Math.floor(this.patNum):this.type==Animator.TYPE.V&&(f=d*(parseInt(this.patNum)+(this.numY?parseInt(this.numY/2):0)));a.save();a.translate(b.x,b.y);a.rotate(b.radian);b.scale&&a.scale(b.scale,b.scale);a.drawImage(this.img,e,f,c,d,-this.hW,-this.hH,c,d);a.restore()};
function AudioMixer(){Repository.apply(this,arguments);this.type="arraybuffer";this.ctx=null;if(window.AudioContext||window.webkitAudioContext)this.ctx=new (window.AudioContext||window.webkitAudioContext);this.dic=[];this.bgm=[];this.lastTime=this.lastKey=null}AudioMixer.prototype=Object.create(Repository.prototype);AudioMixer.INSTANCE=new AudioMixer;AudioMixer.prototype.makeName=function(a){return-1!==navigator.userAgent.toLowerCase().indexOf("edge")?"audio/"+a+".mp3":"audio/"+a+".webm"};
AudioMixer.prototype.onload=function(a,b,c){var d=this;null===this.ctx?this.done():this.ctx.decodeAudioData(c,function(b){d.dic[a]=b;d.done()})};
AudioMixer.prototype.play=function(a){if(null!==this.ctx&&this.dic[a]){var b=arguments.length,c=1<b?arguments[1]:1,d=2<b?arguments[2]:!1,e=3<b?arguments[3]:0,b=4<b?arguments[4]:0,f=this.dic[a],g=new AudioElement(this.ctx,f,b);d&&(g.source.loopEnd=f.duration-.05,g.source.loop=!0,this.bgm.push(g),this.lastKey=a);g.gainNode.gain.value=c;g.setPan(e);this.lastTime=this.ctx.currentTime-b}};AudioMixer.prototype.setPan=function(a){this.bgm.forEach(function(b){b.setPan(a)})};AudioMixer.prototype.fade=function(){this.bgm.forEach(function(a){a.fade()})};
AudioMixer.prototype.stop=function(){this.bgm.forEach(function(a){a.stop()})};AudioMixer.prototype.getCurrentTime=function(){if(0<this.bgm.length){var a=[];this.bgm.forEach(function(b){b.done||a.push(b)});this.bgm=a}return this.bgm.length?this.ctx.currentTime-this.lastTime:null};AudioMixer.prototype.setCurrentTime=function(a){this.bgm.length&&(this.stop(),this.play(this.lastKey,1,!0,0,a))};
function AudioElement(a,b,c){var d=this;this.done=!1;this.source=a.createBufferSource();this.gainNode=a.createGain();this.gainNode.connect(a.destination);"function"==typeof a.createStereoPanner?(this.panNode=a.createStereoPanner(),this.panNode.connect(this.gainNode),this.source.connect(this.panNode)):(this.panNode=null,this.source.connect(this.gainNode));this.source.buffer=b;this.source.start(0,c);this.source.onended=function(){d.done=!0}}
AudioElement.prototype.setPan=function(a){this.panNode&&(this.panNode.pan.value=a)};AudioElement.prototype.fade=function(){var a=this,b=this.gainNode.gain,c=b.value,d=function(){0==Math.floor(100*c)?a.stop():(c*=.9,b.value=c,setTimeout(d,600))};d()};AudioElement.prototype.stop=function(){this.done||this.source.stop()};function Bullet(a,b,c){Actor.apply(this,arguments);this.speed=4;this.height=this.width=8;this.recalculation()}Bullet.prototype=Object.create(Actor.prototype);
Bullet.prototype.draw=function(a){this.walled?this.eject():(a.save(),a.beginPath(),a.fillStyle="rgba(120, 200, 255, 0.7)",a.arc(this.x,this.y,this.width/3,0,2*Math.PI,!1),a.fill(),a.restore())};function Chamber(a,b,c,d){this.type=a;this.cycle=b;this.max=c;this.opt=d;this.reset()}Chamber.prototype.reset=function(){this.tick=0;this.hands=[]};Chamber.prototype.probe=function(){var a=[];this.hands.forEach(function(b){b.isGone||a.push(b)});this.hands=a;this.tick++};
Chamber.prototype.fire=function(a){if(this.tick<this.cycle||this.max<=this.hands.length)return null;a=new this.type(a.field,a.x,a.y,this.opt);this.tick=0;this.hands.push(a);return a};function Enemy(){Actor.apply(this,arguments);this.radian=Math.PI;this.routine=null;this.triggerCycle=this.routineCnt=this.routineIx=0;this.constraint=!1}Enemy.prototype=Object.create(Actor.prototype);Enemy.TRIGGER_CYCLE=30;Enemy.TRIGGER_ALLOWANCE=100;Enemy.MAX_TYPE=127;Enemy.LIST=[];
Enemy.assign=function(a,b,c){a=Object.assign({},Enemy.LIST[a%Enemy.LIST.length]);a.x=b;a.y=c;return a};Enemy.prototype.trigger=function(){if(this.triggerCycle++<Enemy.TRIGGER_CYCLE)return!1;this.triggerCycle=0;return!0};Enemy.prototype.fire=function(a){var b=new Bullet(this.field,this.x,this.y),c=this.calcDistance(a),d=this.field.stage.getFg();b.dir=Math.atan2(a.y-this.y,a.x-this.x+c/b.speed*d.speed);return[b]};Enemy.prototype.actor_move=Actor.prototype.move;
Enemy.prototype.move=function(a){this.routine&&this.routine[this.routineIx].tick(this,a);this.actor_move(a);return this.trigger()&&Enemy.TRIGGER_ALLOWANCE<this.calcDistance(a)?this.constraint?[]:this.fire(a):[]};function Chain(a,b,c){Enemy.apply(this,arguments);this.next=this.prev=null}Chain.prototype=Object.create(Enemy.prototype);Chain.prototype.unshift=function(a){a.next=this;if(a.prev=this.prev)this.prev.next=a;this.prev=a;return this};
Chain.prototype.push=function(a){a.prev=this;if(a.next=this.next)this.next.prev=a;this.next=a;return this};Chain.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;return this.next};
function Field(){this.width=Field.WIDTH;this.height=Field.HEIGHT;this.hW=this.width/2;this.hH=this.height/2;this.ship=new Ship(this,-100,100);this.ship.isGone=!0;this.shipTarget=null;this.shipRemain=0;this.actorList=[];this.enemyCycle=this.hiscore=this.score=0;this.stage=Stage.LIST[0];this.stageNum=0;this.setup()}Field.WIDTH=512;Field.HEIGHT=224;Field.HALF_WIDTH=Field.WIDTH/2;Field.HALF_HEIGHT=Field.HEIGHT/2;Field.MAX_ENEMIES=100;Field.ENEMY_CYCLE=10;Field.MIN_LOOSING_RATE=1;
Field.MAX_LOOSING_RATE=200;Field.MAX_SHIP=7;Field.MAX_HIBERNATE=5*Actor.MAX_EXPLOSION;Field.PHASE={NORMAL:0,BOSS:1};Field.prototype.setup=function(){var a=document.getElementById("canvas");a.width=this.width;a.height=this.height;this.ctx=a.getContext("2d");this.landform=new Landform(a);this.resize()};Field.prototype.resize=function(){var a=document.body.clientWidth/Field.WIDTH,b=window.innerHeight/Field.HEIGHT;document.getElementById("view").setAttribute("style","transform: scale("+(b<a?b:a)+");")};
Field.prototype.nextStage=function(){var a=Stage.LIST[this.stageNum];this.stage=a;this.landform.loadStage(a);this.stageNum++;Stage.LIST.length<=this.stageNum&&(this.stageNum=0)};Field.prototype._reset=function(){this.phase=Field.PHASE.NORMAL;this.ship.reset();this.ship.x=100;this.ship.y=100;this.ship.enter();this.actorList=[this.ship];this.hibernate=Field.MAX_HIBERNATE};Field.prototype.reset=function(){this.landform.reset();this._reset()};Field.prototype.retry=function(){this.landform.retry();this._reset()};
Field.prototype.startGame=function(){document.getElementById("gameOver").classList.add("hidden");this.loosingRate=Field.MAX_LOOSING_RATE;this.score=0;this.shipRemain=Field.MAX_SHIP;this.stageNum=0;this.nextStage();this._reset()};Field.prototype.endGame=function(){document.getElementById("gameOver").classList.remove("hidden")};Field.prototype.isGameOver=function(){return!document.getElementById("gameOver").classList.contains("hidden")};
Field.prototype.inkey=function(a){this.ship.dir=null;if(this.isGameOver())(a[" "]||a.k32)&&this.startGame();else if(!this.ship.explosion){if(a.Control||a.Shift||a.k16||a.k17)this.ship.trigger=!0;this.ship.aim(this.shipTarget);this.ship.inkey(a)}};Field.prototype.moveShipTo=function(a){this.isGameOver()||this.ship.explosion||(a&&(this.ship.trigger=!0),this.shipTarget=a)};
Field.prototype.scroll=function(){var a=this;if(this.phase!=Field.PHASE.BOSS){this.landform.scanEnemy().forEach(function(b){b=b.formation?(new EnmFormation(a,b.x,b.y)).setup(b.type,8):new b.type(a,b.x,b.y);a.actorList.push(b)});var b=this.landform.forward(this.ship);this.isGameOver()||(b==Landform.NEXT.NOTICE?(AudioMixer.INSTANCE.fade(),this.stage.notice()):b==Landform.NEXT.ARRIV?(this.phase=Field.PHASE.BOSS,this.stage.toBossMode()):b==Landform.NEXT.PAST&&this.nextStage(),Field.MIN_LOOSING_RATE<this.loosingRate&&
(this.loosingRate-=this.loosingRate/1E4))}};
Field.prototype.draw=function(){var a=this,b=this.ctx,c=this.ship,d=[],e=[],f=0;b.clearRect(0,0,this.width,this.height);this.landform.drawBg(b);this.actorList.sort(function(a,b){return a.z-b.z});this.actorList.forEach(function(g){if(!g.isGone){g.constraint=0!=parseInt(Math.random()*a.loosingRate/10);var h=g.move(c);h instanceof Array&&h.forEach(function(a){e.push(a)});a.landform.effect(g);a.landform.hitTest(g);g.draw(b);e.push(g);g instanceof Bullet?g.isHit(c):g instanceof Enemy&&(g.isHit(c),d.push(g));
g.explosion&&g.score&&(f+=g.score,g.score=0)}});this.ship.shotList.forEach(function(a){d.forEach(function(b){b.isHit(a)})});this.phase==Field.PHASE.BOSS&&0==d.length&&(this.phase=Field.PHASE.NORMAL,AudioMixer.INSTANCE.fade());this.actorList=e;this.landform.draw();this.score+=f;this.showScore();!this.isGameOver()&&c.isGone&&(AudioMixer.INSTANCE.stop(),0<--this.hibernate||(0<--this.shipRemain?this.retry():this.endGame()))};
Field.prototype.showScore=function(){this.hiscore<this.score&&(this.hiscore=this.score);var a=document.querySelector("#score > div > div:nth-child(2)"),b=document.querySelector("#score > div:nth-child(2) > div:nth-child(2)");document.querySelector("#score > div:nth-child(3)");var c=document.querySelector("#remain > div > div:nth-child(1)");a.innerHTML=this.score;b.innerHTML=this.hiscore;this.shipRemain&&(c.style.width=16*(this.shipRemain-1)+"px")};
function Landform(a){var b=this;this.canvas=a;this.ctx=a.getContext("2d");this.effectH=0;this.next=Landform.NEXT.NONE;this.col=0;this.magni=this.colDir=1;this.target=null;this.ty=this.tx=0;this.selection="b0";this.lastScan=this.brickVal=this.brick=this.which=null;this.touch=!1;this.img=new Image;this.img.onload=function(){b.width=this.width;b.height=this.height;b.bw=this.width/Landform.BRICK_WIDTH;b.bh=this.height/Landform.BRICK_WIDTH;b.viewX=this.width-Field.HALF_WIDTH;b.arrivX=this.width-Field.WIDTH;
b.noticeX=b.arrivX-Field.HALF_WIDTH};this.reverse=new Image;this.reverse.src="./img/reverse.png";this.touch=this.isEdit=!1}Landform.BRICK_WIDTH=8;Landform.BRICK_HALF=Landform.BRICK_WIDTH/2;Landform.BRICK_TYPE={WALL:255,BRITTLE:254};Landform.COL_MAX=512;Landform.NEXT={NONE:0,NOTICE:1,ARRIV:2,IDLE:3,PAST:4};Landform.prototype.load=function(a){a instanceof File&&(this.img.src=window.URL.createObjectURL(a))};
Landform.prototype.loadMapData=function(a){var b=this,c=new Image;c.onload=function(){var a=document.createElement("canvas"),e=a.getContext("2d");a.width=this.width;a.height=this.height;e.drawImage(c,0,0);b.brick=e.getImageData(0,0,this.width,this.height);b.touch=!0};c.src=a instanceof File?window.URL.createObjectURL(a):a};Landform.prototype.loadStage=function(a){var b=a.getFg();this.stage=a;this.loadMapData("./img/"+a.map);this.img.src=b.img.src;this.reset()};
Landform.prototype.reset=function(){this.next=Landform.NEXT.NONE;this.stage&&this.stage.reset()};Landform.prototype.retry=function(){this.next=Landform.NEXT.NONE;this.stage&&(this.stage.retry(),this.loadMapData("./img/"+this.stage.map))};
Landform.prototype.effect=function(a){var b=Math.max(a.field.width+a.width,a.maxX);a.effectH&&(a.x-=this.effectH);a.effectV&&this.next==Landform.NEXT.NONE&&(a.y+=this.stage.effectV);(a.x<a.minX||b<a.x)&&a.eject();this.stage.scroll==Stage.SCROLL.OFF?(a.y<a.minY||a.maxY<a.y)&&a.eject():this.stage.scroll==Stage.SCROLL.ON?(a.y<-this.height||this.height+a.maxY<a.y)&&a.eject():a.gravity&&Landform.BRICK_WIDTH+Landform.BRICK_HALF<Math.abs(a.dy*a.speed)?a.eject():0>a.y?a.y+=this.height:this.height<a.y&&(a.y-=
this.height)};
Landform.prototype.forward=function(a){if(!this.width)return Landform.NEXT.NONE;var b=this.stage.getFg();this.next!=Landform.NEXT.ARRIV&&this.stage.scrollV(a);if(this.viewX<=b.x)return this.effectH=0,this.next!=Landform.NEXT.PAST?this.next=Landform.NEXT.PAST:Landform.NEXT.NONE;this.stage.forward();this.effectH=b.effectH;if(this.arrivX<=b.x){if(this.next==Landform.NEXT.NOTICE)return b.x=this.arrivX,this.effectH=0,this.next=Landform.NEXT.ARRIV;if(this.arrivX<b.x)return this.next=Landform.NEXT.IDLE}else if(this.noticeX<=b.x&&
this.next!=Landform.NEXT.NOTICE)return this.next=Landform.NEXT.NOTICE;return Landform.NEXT.NONE};
Landform.prototype.scanEnemy=function(){var a=[];if(!this.brick||this.next==Landform.NEXT.IDLE)return a;var b=this.stage.getFg(),c=b.x,b=b.y,d=Math.round((c+Field.WIDTH-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(0>d||d===this.lastScan)return a;this.lastScan=d;for(var e=Field.WIDTH+Landform.BRICK_WIDTH,f=0;f<this.bh;f++){var g=f*this.bw*4+4*d,g=this.brick.data[g+1];if(0<g&&g<=Enemy.MAX_TYPE){var h=-b+(f+1)*Landform.BRICK_WIDTH;a.push(Enemy.assign(g-1,e,h))}}d=Math.round(c/Landform.BRICK_WIDTH);
if(0>d)return a;for(f=0;f<this.bh;f++)g=f*this.bw*4+4*d,g=this.brick.data[g+1],Enemy.MAX_TYPE<g&&(h=-b+(f+1)*Landform.BRICK_WIDTH,a.push(Enemy.assign(g-1-Enemy.MAX_TYPE,0,h)));return a};Landform.prototype.hitTest=function(a){this.brick&&(a.walled=this.getBrick(a,2),this.target=a)};Landform.prototype.smashWall=function(a){this.stage.getFg().smashWall(a);this.putBrick(a,2,0)};
Landform.prototype.scanFloor=function(a){if(this.brick){var b,c=this.getBrick(a,2),d=0>a.gravity?-1:1;if(0<c){for(b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;0<c;)b-=Landform.BRICK_WIDTH*d,c={x:a.x,y:b},c=this.getBrick(c,2);b+=Landform.BRICK_WIDTH*d}else if(b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,0>d){for(;0<b&&!c;)b-=Landform.BRICK_WIDTH,c={x:a.x,y:b},c=this.getBrick(c,2);c||(b=-a.height-Landform.BRICK_WIDTH)}else{for(;b<this.height&&!c;)b+=Landform.BRICK_WIDTH,
c={x:a.x,y:b},c=this.getBrick(c,2);c||(b=this.height+a.height+Landform.BRICK_WIDTH)}return b}};Landform.prototype.getHorizontalAngle=function(a){var b={x:a.x+Landform.BRICK_WIDTH,y:a.y-2*Landform.BRICK_WIDTH},c=this.scanFloor({x:a.x-Landform.BRICK_WIDTH,y:a.y-2*Landform.BRICK_WIDTH}),b=this.scanFloor(b);return Math.atan2(b-c,a.width)};
Landform.prototype.getBrickIndex=function(a){var b=this.stage.getFg(),c=Math.round((b.x+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(0>c||this.bw<c)return-1;a=Math.round((b.y+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);a%=this.bh;return a*this.bw*4+4*c};Landform.prototype.getBrick=function(a,b){if(!this.brick)return null;var c=this.getBrickIndex(a);return 0>c?null:this.brick.data[c+b]};
Landform.prototype.wheel=function(a){var b=this.stage.getFg();0>a?(b.y+=Landform.BRICK_WIDTH,this.height<=b.y&&(b.y=0)):(0==b.y&&(b.y=this.height),b.y-=Landform.BRICK_WIDTH)};Landform.prototype.putBrick=function(a,b,c){a=this.getBrickIndex(a);0>a||(this.brick.data[a+b]=c,this.brick.data[a+3]=c?255:0)};
Landform.prototype.drawEnemy=function(a,b,c){var d=Enemy.MAX_TYPE<a;a=Enemy.LIST[(d?a-Enemy.MAX_TYPE:a)-1];var e=a.formation?3:1,f=a.instance,g=this.ctx;if(!a.instance)return null;f.x=b+f.hW;for(f.y=c+f.hH;e--;)f.draw(g),f.x+=2,f.y+=2;d&&(g.save(),g.translate(f.x,f.y),g.drawImage(this.reverse,-8,-4),g.restore());return f};
Landform.prototype.drawTarget=function(){if(this.isEdit&&this.target){var a=Math.round((this.target.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,b=Math.round((this.target.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,c=this.ctx,d=Landform.BRICK_WIDTH,e=parseInt(this.selection);0<e&&(e=this.drawEnemy(e,a,b))&&(d=e.width);c.save();c.fillStyle="rgba(128, 255, 255, .4)";c.fillRect(a,b,d,d);c.restore();this.touchDown(a,b)}};
Landform.prototype.touchDown=function(a,b){if(!this.which)this.ty=this.tx=-1,this.brickVal=null;else if(this.tx!=a||this.ty!=b){var c=parseInt(this.selection);if(0<c){var d=this.getBrick(this.target,1),e=d-Enemy.MAX_TYPE;!d||d!=c&&e!=c?this.putBrick(this.target,1,c):d==c?this.putBrick(this.target,1,c+Enemy.MAX_TYPE):this.putBrick(this.target,1,0)}else d=this.getBrick(this.target,2),c=this.selection.substr(1),null==this.brickVal&&(this.brickVal=0<d?0:255-c),this.putBrick(this.target,2,this.brickVal);
this.touch=!0;this.tx=a;this.ty=b}};
Landform.prototype.drawBrick=function(){if(this.brick&&this.isEdit){var a=this.stage.getFg(),b=a.x,c=a.y,a=this.ctx,d=255<this.col?this.col-256:0,e=255<this.col?255:this.col%256,f=Landform.BRICK_WIDTH-2,g=Math.round(b/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,h=g/Landform.BRICK_WIDTH,k=Math.min(h+512/Landform.BRICK_WIDTH,this.bw),l=Math.round(c/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH/Landform.BRICK_WIDTH,n=this.brick.data;a.save();a.translate(-b,-c);a.strokeStyle="rgba("+d+", "+e+", 255, .4)";
a.fillStyle=a.strokeStyle;for(c=0;c<this.bh;c++)for(var e=l+c,d=e*Landform.BRICK_WIDTH,e=4*(e%this.bh*this.bw+h),p=h,q=g;p<k;p++,q+=Landform.BRICK_WIDTH,e+=4)if(!(0>p)){var m=n[e+1];m&&this.drawEnemy(m,q,d);m=n[e+2];if(255==m)a.fillRect(q,d,f,f);else if(254==m){var m=q+Landform.BRICK_HALF-1,r=d+Landform.BRICK_HALF-1;a.beginPath();a.arc(m,r,f/2,0,Math.PI2,!1);a.stroke();a.strokeRect(q,d,f,f)}}this.width-Field.WIDTH<=b&&(p=this.width-Landform.BRICK_WIDTH,a.fillStyle="rgba(255, 0, 0, .4)",a.fillRect(p,
0,Landform.BRICK_WIDTH,this.height));a.restore();this.col+=16*this.colDir;if(0>=this.col||Landform.COL_MAX<=this.col)this.colDir*=-1}};Landform.prototype.drawBg=function(a){this.stage&&(a.save(),a.scale(this.magni,this.magni),this.stage.drawBg(a),a.restore())};
Landform.prototype.draw=function(){if(this.stage){var a=this.ctx;a.save();a.scale(this.magni,this.magni);this.stage.drawFg(a);this.drawBrick();this.drawTarget();a.restore();this.brick&&this.isEdit&&this.touch&&this.brick&&(this.updateMap(),this.touch=!1)}};
Landform.prototype.updateMap=function(){var a=document.getElementById("mapImage");if(a){var b=document.createElement("canvas"),c=b.getContext("2d");b.width=this.brick.width;b.height=this.brick.height;c.putImageData(this.brick,0,0);a.setAttribute("src",b.toDataURL("image/png"))}};Landform.prototype.getImageData=function(){var a=document.createElement("canvas"),b=a.getContext("2d");a.width=this.width;a.height=this.height;b.drawImage(this.img,0,0);return b.getImageData(0,0,this.width,this.height)};
Landform.prototype.getBrickData=function(a){return null!=this.brick?this.brick:a.createImageData(this.width/Landform.BRICK_WIDTH,this.height/Landform.BRICK_WIDTH)};
Landform.prototype.generateBrick=function(a){if(this.img.src&&this.img.complete){var b=this.getImageData(),c=this.width/Landform.BRICK_WIDTH,d=this.height/Landform.BRICK_WIDTH;a=this.getBrickData(a);var e=a.data,f=this.width*Landform.BRICK_HALF+4*Landform.BRICK_HALF,g=0;console.log(this.width+" x "+this.height+" | "+this.width*this.height*4);console.log(c+" x "+d+" | "+e.length);for(var h=0;h<d;h++){for(var k=0;k<c;k++){for(var l=!1,n=0;4>n;n++)b.data[f+n]&&(l=!0);l=l?255:0;e[g+2]=l;e[g+3]=l;f+=4*
Landform.BRICK_WIDTH;g+=4}f+=this.width*(Landform.BRICK_WIDTH-1)*4}console.log("ix:"+g);console.log("sx:"+f);this.brick=a;this.touch=!0}};Math.PI2=Math.PI2||2*Math.PI;Math.SQ=Math.SQ||Math.PI/2;Math.trim=Math.trim||function(a){for(;Math.PI<a;)a-=Math.PI2;for(;a<-Math.PI;)a+=Math.PI2;return a};Math.close=Math.close||function(a,b,c){b=Math.trim(a-b);return Math.abs(b)<=c?a:0<b?a-c:a+c};function Matrix(a){this.mat=a}Matrix.NO_EFFECT=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]];
Matrix.rotateX=function(a){return new Matrix([[1,0,0,0],[0,Math.cos(a),-Math.sin(a),0],[0,Math.sin(a),Math.cos(a),0],[0,0,0,1]])};Matrix.rotateY=function(a){return new Matrix([[Math.cos(a),0,Math.sin(a),0],[0,1,0,0],[-Math.sin(a),0,Math.cos(a),0],[0,0,0,1]])};Matrix.rotateZ=function(a){return new Matrix([[Math.cos(a),-Math.sin(a),0,0],[Math.sin(a),Math.cos(a),0,0],[0,0,1,0],[0,0,0,1]])};
Matrix.prototype.multiply=function(a){var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=a.mat;this.mat.forEach(function(a,e){a.forEach(function(d,g){for(var f=0,k=0;4>k;k++)f+=a[k]*c[k][g];b[e][g]=f})});return new Matrix(b)};Matrix.prototype.affine=function(a,b,c){var d=this.mat;return{x:d[0][0]*a+d[0][1]*b+d[0][2]*c+d[0][3],y:d[1][0]*a+d[1][1]*b+d[1][2]*c+d[1][3],z:d[2][0]*a+d[2][1]*b+d[2][2]*c+d[2][3]}};
var Matter=function(){this.y=this.x=0},Missile=function(a,b,c,d){Actor.call(this,a,b,c);this.dir=d.dir;this.speed=6;this.height=this.width=8;this.gravity=d.gravity;this.recalculation()};$jscomp.inherits(Missile,Actor);Missile.prototype.fate=function(){this.x=this.field.width+this.width;this.isGone=!0};Missile.prototype.draw=function(a){a.save();a.beginPath();a.fillStyle="rgba(200, 200, 255, 0.6)";a.arc(this.x,this.y,this.width/3,0,2*Math.PI,!1);a.fill();a.restore()};
function Gizmo(a,b){this.type=a;this.destination=b}Gizmo.TYPE={FIXED:0,OWN:1,AIM:2,CHASE:3};Gizmo.DEST={TO:0,TO_X:1,TO_Y:2,ROTATE:3,ROTATE_L:4,ROTATE_R:5,LEFT:6,RIGHT:7};
Gizmo.prototype.tick=function(a,b){if(this.type==Gizmo.TYPE.FIXED)this.destination==Gizmo.DEST.ROTATE?a.radian=a.dir:a.dir=null;else if(this.type==Gizmo.TYPE.OWN)this.destination==Gizmo.DEST.ROTATE_L?a.dir-=a.step:this.destination==Gizmo.DEST.ROTATE_R?a.dir+=a.step:this.destination==Gizmo.DEST.LEFT?a.dir=Math.PI:this.destination==Gizmo.DEST.RIGHT&&(a.dir=0);else{var c=b.x-a.x,d=b.y-a.y;Math.abs(c)<=a.speed&&(c=0);Math.abs(d)<=a.speed&&(d=0);if(this.type==Gizmo.TYPE.AIM)if(this.destination==Gizmo.DEST.TO_X)a.radian=
0>c?Math.PI:0;else if(this.destination==Gizmo.DEST.TO_Y)a.radian=0>c?-Math.SQ:Math.SQ;else{if(this.destination==Gizmo.DEST.ROTATE){var e=a.calcDistance(b);a.speed<e&&(e=Math.PI/30,a.radian=Math.close(a.radian,Math.atan2(d,c),e),a.radian=Math.trim(a.radian))}}else this.type==Gizmo.TYPE.CHASE&&(this.destination==Gizmo.DEST.TO?a.dir=Math.atan2(d,c):this.destination==Gizmo.DEST.TO_X&&c?a.dir=Math.atan2(0,c):this.destination==Gizmo.DEST.TO_Y&&d?a.dir=Math.atan2(d,0):this.destination==Gizmo.DEST.ROTATE&&
(e=Math.PI/60,a.dir=Math.close(a.dir,Math.atan2(d,c),e),a.radian=a.dir))}};function Movement(a){var b=parseInt(a);this.cond=a;this.count=b==a?b:null;this.list=[]}Movement.COND={X:"x",Y:"y"};Movement.prototype.add=function(a,b){this.list.push(new Gizmo(a,b));return this};
Movement.prototype.isValid=function(a,b){if(this.cond){if(this.count){if(a.routineCnt++<this.count)return!0;a.routineCnt=0;return!1}var c=b.x-a.x,d=b.y-a.y;return this.cond==Movement.COND.X&&Math.abs(c)<=a.speed||this.cond==Movement.COND.Y&&Math.abs(d)<=a.speed?!1:!0}};Movement.prototype.tick=function(a,b){this.list.forEach(function(c){c.tick(a,b)});this.isValid(a,b)||(a.routineIx++,a.routine.length<=a.routineIx&&(a.routineIx=0))};
function Repository(){this.loaded=this.max=0;this.dic={};this.reserved={};this.type="json"}Repository.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};Repository.prototype.reserve=function(a){var b=this;a.forEach(function(a){null==a||a in b.reserved||(b.reserved[a]=!0,b.load(a))})};Repository.prototype.makeName=function(a){return a};
Repository.prototype.load=function(a){var b=this,c=new XMLHttpRequest,d=this.makeName(a);this.max++;c.open("GET",d,!0);c.responseType=this.type;c.addEventListener("loadend",function(){var e=c.response;b.dic[a]=e;b.onload(a,d,e)});c.send()};Repository.prototype.onload=function(a,b,c){this.done()};Repository.prototype.done=function(){this.loaded++};
function Ship(a,b,c){Actor.apply(this,arguments);this.speed=4;this.effectH=!1;this.shotList=[];this.chamberList=[new Chamber(Shot,2,Ship.MAX_SHOTS),new Chamber(Missile,8,2,{gravity:.1,dir:0}),new Chamber(Missile,8,2,{gravity:-.1,dir:0}),new Chamber(Missile,8,2,{gravity:.1,dir:Math.PI}),new Chamber(Missile,8,2,{gravity:-.1,dir:Math.PI})];this.anim=new Animator(this,"ship001.png",Animator.TYPE.V,1,2*Ship.PATTERNS+1);this.reset()}Ship.MAX_SHOTS=7;Ship.PATTERNS=2;Ship.prototype=Object.create(Actor.prototype);
Ship.prototype._recalculation=Actor.prototype.recalculation;Ship.prototype.recalculation=function(){this.right=this.field.width-3*this.width;this.bottom=this.field.height-this.hH;this._recalculation()};Ship.prototype.reset=function(){this.trigger=!1;this.chamberList.forEach(function(a){a.reset()});this.shotList=[]};
Ship.prototype.inkey=function(a){var b=!1,c=0;if(a.ArrowLeft||a.Left||a.k37)c=1,b=!0;else if(a.ArrowRight||a.Right||a.k39)c=-1,b=!0;if(a.ArrowUp||a.Up||a.k38)c=2-.5*c,b=!0;else if(a.ArrowDown||a.Down||a.k40)c*=.5,b=!0;b&&(this.dir=(c+1)*Math.SQ)};Ship.prototype.sieveShots=function(){var a=[];this.shotList.forEach(function(b){b.isGone||a.push(b)});this.shotList=a};Ship.prototype._move=Actor.prototype.move;
Ship.prototype.move=function(){this._move();this.chamberList.forEach(function(a){a.probe()});if(!this.isGone)if(this.walled)this.fate();else{if(this.x<this.hW||this.right<this.x)this.x=this.svX;if(this.y<this.hH||this.bottom<this.y)this.y=this.svY;var a=this;this.sieveShots();if(this.trigger){var b=[];this.trigger=!1;this.chamberList.forEach(function(c){if(c=c.fire(a))a.shotList.push(c),b.push(c)});return b}}};
function Shot(){Actor.apply(this,arguments);this.dir=0;this.width=16;this.height=8;this.recalculation();this.speed=12;this.effectH=!1;this.size=2;this.maxX=this.field.width;AudioMixer.INSTANCE.play("sfx-fire",.4,!1,(this.x-Field.HALF_WIDTH)/Field.HALF_WIDTH)}Shot.prototype=Object.create(Actor.prototype);Shot.prototype.fate=function(){this.x=this.field.width+this.width;this.isGone=!0};
Shot.prototype.draw=function(a){a.beginPath();a.fillStyle="rgba(255, 255, 0, 0.7)";a.arc(this.x,this.y,this.size,0,2*Math.PI,!1);a.fill();this.walled&&(this.walled==Landform.BRICK_TYPE.BRITTLE&&this.field.landform.smashWall(this),this.fate())};function Stage(a,b,c){var d=this;this.scrollSv=this.scroll=a;this.map=b;this.view=c;this.boss=this.bgm=this.fg=null;this.checkPoint=0;this.view.forEach(function(a){a.stage=d});this.effectV=this.effectH=0}Stage.SCROLL={OFF:0,ON:1,LOOP:2,TOP:4,BOTTOM:8};
Stage.LIST=[];Stage.CHECK_POINT=[660,1440];Stage.prototype.setBgm=function(a){var b=arguments.length;this.bgm=a;this.boss=1<b?arguments[1]:null;AudioMixer.INSTANCE.reserve([this.bgm,this.boss]);return this};Stage.prototype.playBgm=function(){this.bgm&&AudioMixer.INSTANCE.play(this.bgm,.7,!0)};Stage.prototype.getFg=function(){if(this.fg)return this.fg;var a;this.view.forEach(function(b){b instanceof StageFg&&(a=b)});return this.fg=a};Stage.prototype.reset=function(){this.checkPoint=0;this.retry()};
Stage.prototype.retry=function(){var a=this;this.scroll=this.scrollSv;this.effectV=this.effectH=0;this.view.forEach(function(b){b.reset(a.checkPoint)});this.playBgm()};
Stage.prototype.scrollV=function(a){this.effectV=0;if(this.scroll!=Stage.SCROLL.OFF){var b=a.field.hH-a.y;a=this.getFg();if(this.scroll==Stage.SCROLL.TOP)b=5*a.speed;else if(this.scroll==Stage.SCROLL.BOTTOM)b=5*-a.speed;else if(Math.abs(b)<a.speed)return;var b=b/3,c=a.y-b;if(this.scroll!=Stage.SCROLL.ON||!(0>c||a.viewY<c))if(this.scroll==Stage.SCROLL.TOP&&0>c)this.scroll=Stage.SCROLL.OFF;else{if(this.scroll==Stage.SCROLL.BOTTOM&&(console.log("nextY:"+c+"/"+a.height),a.viewY<c)){this.scroll=Stage.SCROLL.OFF;
return}this.effectV=b}}};Stage.prototype.forward=function(a){var b=this;this.view.forEach(function(b){b.forward(a)});var c=this.getFg().x;Stage.CHECK_POINT.forEach(function(a){a<=c&&b.checkPoint<c&&(b.checkPoint=a)})};Stage.prototype.drawBg=function(a){this.view.forEach(function(b){b instanceof StageFg||b.draw(a)})};Stage.prototype.drawFg=function(a){this.view.forEach(function(b){b instanceof StageBg||b.draw(a)})};
Stage.prototype.notice=function(){if(this.scroll==Stage.SCROLL.ON||this.scroll==Stage.SCROLL.LOOP){var a=this.getFg();this.scroll=a.y<a.height/2?Stage.SCROLL.TOP:Stage.SCROLL.BOTTOM}};Stage.prototype.toBossMode=function(){this.boss&&AudioMixer.INSTANCE.play(this.boss,.7,!0)};
function StageView(a){var b=this,c=arguments.length;this.ready=!1;this.pattern=null;this.repeatX=2;this.img=new Image;this.img.src="./img/"+a;this.img.onload=function(){b.width=this.width;b.height=this.height;b.w2=this.width*b.repeatX;b.h2=2*this.height;b.viewX=this.width-Field.HALF_WIDTH;b.viewY=this.height-Field.HEIGHT;b.ready=!0};this.speed=1<c?arguments[1]:1;this.dir=2<c?arguments[2]:0;this.blink=3<c?arguments[3]:0;this.reset()}
StageView.prototype.reset=function(a){this.x=a%this.width;this.effectV=this.effectH=this.y=0;this.alpha=1;this.blinkDir=-1};
StageView.prototype.forward=function(){var a=this.stage.effectV;this.effectH=Math.cos(this.dir)*this.speed;this.effectV=Math.sin(this.dir)*this.speed;this.x+=this.effectH;this.y+=this.effectV;this.y-=a*this.speed;this.width<this.x&&(this.x-=this.width);0>this.y&&(this.y+=this.height);this.height<this.y&&(this.y-=this.height);this.blink&&(this.alpha+=this.blinkDir*this.blink,.3>=this.alpha||1<=this.alpha)&&(this.blinkDir*=-1)};
StageView.prototype.getPattern=function(a,b){!this.pattern&&this.ready&&(this.pattern=a.createPattern(b,"repeat"));return this.pattern};StageView.prototype.draw=function(a){a.save();a.globalAlpha=this.alpha;a.translate(-this.x,-this.y);a.beginPath();a.fillStyle=this.getPattern(a,this.img);a.rect(0,0,this.w2,this.h2);a.fill();a.restore()};function StageFg(){StageView.apply(this,arguments);this.repeatX=1;this.bmp=this.img}StageFg.prototype=Object.create(StageView.prototype);
StageFg.prototype.createCanvas=function(){var a=document.createElement("canvas"),b=a.getContext("2d");a.width=this.width;a.height=this.height;b.clearRect(0,0,this.width,this.height);b.drawImage(this.img,0,0);return a};StageFg.prototype._reset=StageView.prototype.reset;StageFg.prototype.reset=function(a){this._reset(a);0==a&&(this.x=-Field.WIDTH);this.ready&&(this.canvas=this.createCanvas(),this.pattern=canvas.getContext("2d").createPattern(this.canvas,"repeat"))};
StageFg.prototype.smashWall=function(a){var b=Math.round((this.x+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;a=Math.round((this.y+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var c=this.canvas.getContext("2d");a%=this.height;c.clearRect(b,a,Landform.BRICK_WIDTH,Landform.BRICK_WIDTH);this.pattern=c.createPattern(this.canvas,"repeat")};function StageBg(){StageView.apply(this,arguments)}StageBg.prototype=Object.create(StageView.prototype);
